$(document).ready(function() {

	


	// var events_array = [{
 //        title: "",
 //        start: '2016-07-14 06:15:00',
 //        end: '2016-07-14 06:30:00',
 //        resourceId:'e',
 //        patient_firstName: "Sean",
 //        patient_lastName: "Dean",
 //        doctor_firstName: "John",
 //        doctor_lastName: "Kim",
 //        reason: "",
 //        notes: "",
 //        icon: 'icons/heart-checkup.png',
 //        office: "F",
 //        procedure: "Lap-band",
 //        status: "",
 //        color: "grey",
 //    },
 //    {
 //        title: "",
 //        start: '2016-07-14 06:15:00',
 //        end: '2016-07-14 06:30:00',
 //        resourceId:'b',
 //        patient_firstName: "Sean",
 //        patient_lastName: "Dean",
 //        doctor_firstName: "John",
 //        doctor_lastName: "Kim",
 //        reason: "",
 //        notes: "",
 //        icon: 'icons/heart-checkup.png',
 //        office: "F",
 //        procedure: "Lap-band",
 //        status: "",
 //        color: "gold",
 //    },
 //    {
 //        title: "",
 //        start: '2016-07-14 06:15:00',
 //        end: '2016-07-14 06:30:00',
 //        resourceId:'b',
 //        patient_firstName: "Sean",
 //        patient_lastName: "Dean",
 //        doctor_firstName: "John",
 //        doctor_lastName: "Kim",
 //        reason: "",
 //        notes: "",
 //        icon: 'icons/heart-checkup.png',
 //        office: "F",
 //        procedure: "Lap-band",
 //        status: "",
 //        color: "gold",
 //    },
 //    {
 //        title: "",
 //        start: '2016-07-15 06:15:00',
 //        end: '2016-07-15 06:30:00',
 //        resourceId:'d',
 //        patient_firstName: "Sean",
 //        patient_lastName: "Dean",
 //        doctor_firstName: "John",
 //        doctor_lastName: "Kim",
 //        reason: "",
 //        notes: "",
 //        icon: 'icons/heart-checkup.png',
 //        office: "F",
 //        procedure: "Lap-band",
 //        status: "",
 //        color: "green",
 //    },              
 //    {
 //        title: "",
 //        start: '2016-07-14 14:00:00',
 //        end: '2016-07-14 14:30:00',
 //        resourceId:'c',
 //        patient_firstName: "Sean",
 //        patient_lastName: "Dean",
 //        doctor_firstName: "John",
 //        doctor_lastName: "Kim",
 //        reason: "",
 //        notes: "",
 //        icon: 'icons/heart-checkup.png',
 //        office: "B",
 //        procedure: "Lap-band",
 //        status: "",
 //        color: "red",
 //    },
 //    {
 //        title: "",
 //        start: '2016-07-14 14:00:00',
 //        end: '2016-07-14 14:30:00',
 //        resourceId:'d',
 //        patient_firstName: "Sean",
 //        patient_lastName: "Dean",
 //        doctor_firstName: "John",
 //        doctor_lastName: "Kim",
 //        reason: "",
 //        notes: "",
 //        icon: 'icons/heart-checkup.png',
 //        office: "B",
 //        procedure: "Lap-band",
 //        status: "",
 //        color: "green",
 //    },
 //    {
 //        title: "",
 //        start: '2016-07-14 07:00:00',
 //        end: '2016-07-14 07:15:00',
 //        resourceId:'e',
 //        patient_firstName: "Sean",
 //        patient_lastName: "Dean",
 //        doctor_firstName: "John",
 //        doctor_lastName: "Kim",
 //        reason: "",
 //        notes: "",
 //        icon: 'icons/heart-checkup.png',
 //        office: "F",
 //        procedure: "Lap-band",
 //        status: "",
 //        color: "orange",
 //    },
 //    {
 //        title: "",
 //        start: '2016-07-14 06:00:00',
 //        end: '2016-07-14 06:30:00',
 //        resourceId:'a',
 //        patient_firstName: "Sean",
 //        patient_lastName: "Dean",
 //        doctor_firstName: "John",
 //        doctor_lastName: "Kim",
 //        reason: "",
 //        notes: "",
 //        icon: 'icons/heart-checkup.png',
 //        office: "F",
 //        procedure: "Lap-band",
 //        status: "",
 //        color: "yellow",
 //    },
 //    {
 //        title: "",
 //        start: '2016-07-14 06:00:00',
 //        end: '2016-07-14 06:30:00',
 //        resourceId:'c',
 //        patient_firstName: "Sean",
 //        patient_lastName: "Dean",
 //        doctor_firstName: "John",
 //        doctor_lastName: "Kim",
 //        reason: "",
 //        notes: "",
 //        icon: 'icons/heart-checkup.png',
 //        office: "B",
 //        procedure: "Lap-band",
 //        status: "",
 //        color: "royalblue",
 //    },
 //    {
 //        title: "",
 //        start: '2016-07-14 06:45:00',
 //        end: '2016-07-14 07:00:00',
 //        resourceId: 'e',
 //        patient_firstName: "Sean",
 //        patient_lastName: "Dean",
 //        doctor_firstName: "John",
 //        doctor_lastName: "Lee",
 //        reason: "",
 //        notes: "",
 //        icon: "",
 //        office: "B",
 //        procedure: "Braces",
 //        status: "",
 //        color: "mediumorchid",
 //    }
 //  ];

	// var events_array = [{
	//   "appointments": [
	//     {
	//     	"start" : "",
	//     	"end" : "",
	//       "id": 001,
	//       "patient_id": 101,
	//       "rescheduled_at": "",
	//       "staff_id": 010,
	//       "status": "exercitation ut enim Duis",
	//       "time": "dolor",
	//     },
	//     {
	//     	"start" : "",
	//     	"end" : "",
	//       "id": 002,
	//       "patient_id": 102,
	//       "rescheduled_at": "",
	//       "staff_id": 020,
	//       "status": "exercitation ut enim Duis",
	//       "time": "dolor",
	//     },
	//     {
	//     	"start" : "",
	//     	"end" : "",
	//       "id": 003,
	//       "patient_id": 103,
	//       "rescheduled_at": "",
	//       "staff_id": 030,
	//       "status": "exercitation ut enim Duis",
	//       "time": "dolor",
	//     },
	//     {
	//     	"start" : "",
	//     	"end" : "",
	//       "id": 004,
	//       "patient_id": 104,
	//       "rescheduled_at": "",
	//       "staff_id": 040,
	//       "status": "exercitation ut enim Duis",
	//       "time": "dolor",
	//     },
	//   ],
	//   "classes": [
	//     {
	//       "attendees": ["parvati", "amanda", "cerie"],
	//       "start": "",
	//       "end" : "",
	//       "id": 2.1188895e+07,
	//       "staff_id": 030,
	//       "time": "Duis dolore",
	//       "title": "anim",
	//     },
	//     {
	//       "attendees": ["eliza", "ami", "fairplay", "kathy", "mikey", "chet"],
	//       "start": "",
	//       "end" : "",
	//       "id": 2.1188895e+07,
	//       "staff_id": 030,
	//       "time": "Duis dolore",
	//       "title": "anim",
	//     },
	//     {
	//       "attendees": ["ozzy", "james", "jason", "eric"],
	//       "start": "",
	//       "end" : "",
	//       "id": 2.1188895e+07,
	//       "staff_id": 020,
	//       "time": "Duis dolore",
	//       "title": "anim",
	//     },
	//   ],
	//   "time-blocks": [
	//     {
	//       "staff_id": "",
	//       "client_id": "", //location
	//       "start": "",
	//       "end" : "",
	//     }
	//   ]
	// }];



	// $('#calendar').fullCalendar({

 //    schedulerLicenseKey: 'CC-Attribution-NonCommercial-NoDerivatives',
 //    defaultView: 'agendaDay',
    
 //    slotDuration: {minutes: 15}, //required
 //    //events: events_array,
 //    header: {
 //        left: 'title',
 //        center: 'prev,next today',
 //        right:  'month,agendaWeek,agendaDay'
 //    },
 //    eventLimit: true,
 //    events: calendarData.appointments,
 //    viewRender: function() {
 //    	var viewNow = $('#calendar').fullCalendar('getView');
 //    	if(viewNow.type === "agendaDay") {
 //    		$('tbody.fc-body').css('display', 'none');
 //    		// $('tbody.fc-body').before('<table id="dayAgenda-display"><thead id="dayAgenda-display-head"><tr><td>what</td></tr></thead><tbody id="dayAgenda-display-body"></tbody></table>')
 //    	}
 //    },


 //   })




})